const SEARCH_MOVIE = 'SEARCH_MOVIE';
const FETCH_MOVIES = 'FETCH_MOVIES';
const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
const LOADING = 'LOADING'

export {SEARCH_MOVIE, FETCH_MOVIES,FETCH_MOVIE_DETAILS, LOADING}